"use client";

const reports = [
  {
    id: 1,
    title: "Weekly Customer Feedback Report",
    period: "Aug 18, 2026 – Aug 24, 2026",
    generatedBy: "Admin",
    date: "Aug 24, 2026",
  },
  {
    id: 2,
    title: "Monthly Voice of Customer Report",
    period: "Aug 1, 2026 – Aug 24, 2026",
    generatedBy: "Admin",
    date: "Aug 24, 2026",
  },
  {
    id: 3,
    title: "Customer Experience Summary",
    period: "Jul 1, 2026 – Jul 31, 2026",
    generatedBy: "Analyst",
    date: "Aug 1, 2026",
  },
];

export default function ReportsPage() {
  return (
    <main className="min-h-screen bg-gray-100 p-8 text-gray-900">

      <div className="max-w-6xl">

        {/* Header */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">

          <div>
            <h1 className="text-3xl font-bold">
              VoC Reports
            </h1>

            <p className="mt-2 text-gray-600">
              View previously generated Voice-of-Customer reports.
            </p>
          </div>

          <a
            href="/reports/new"
            className="rounded-lg bg-gray-900 px-5 py-3 text-center font-medium text-white hover:bg-gray-800"
          >
            + Generate Report
          </a>

        </div>

        {/* Reports List */}
        <div className="mt-8 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">

          <div className="border-b border-gray-200 bg-gray-50 px-6 py-4">
            <h2 className="font-semibold">
              Generated Reports
            </h2>
          </div>

          <div className="divide-y divide-gray-200">

            {reports.map((report) => (
              <div
                key={report.id}
                className="flex flex-col gap-5 p-6 transition hover:bg-gray-50 md:flex-row md:items-center md:justify-between"
              >

                {/* Report Information */}
                <div>

                  <h3 className="text-lg font-semibold">
                    {report.title}
                  </h3>

                  <div className="mt-2 space-y-1 text-sm text-gray-500">

                    <p>
                      <span className="font-medium text-gray-700">
                        Period:
                      </span>{" "}
                      {report.period}
                    </p>

                    <p>
                      <span className="font-medium text-gray-700">
                        Generated by:
                      </span>{" "}
                      {report.generatedBy}
                    </p>

                    <p>
                      <span className="font-medium text-gray-700">
                        Generated:
                      </span>{" "}
                      {report.date}
                    </p>

                  </div>

                </div>

                {/* Open Button */}
                <a
                  href={`/reports/${report.id}`}
                  className="rounded-lg border border-gray-300 bg-white px-5 py-3 text-center font-medium text-gray-800 hover:bg-gray-100"
                >
                  Open Report
                </a>

              </div>
            ))}

          </div>

        </div>

        {/* Information */}
        <div className="mt-6 rounded-xl border border-gray-200 bg-white p-6 shadow-sm">

          <h2 className="font-semibold">
            About VoC Reports
          </h2>

          <p className="mt-2 text-sm leading-6 text-gray-600">
            Voice-of-Customer reports summarize feedback themes,
            sentiment changes, customer quotes, and recommended actions.
          </p>

        </div>

      </div>

    </main>
  );
}